version: '3.8'
services:
  mysql:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: mysql_db
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
